includes:
  - base.yaml
model:
  model_name: GSATGIN
  global_pool: sum
ood:
  ood_alg: GSAT
  ood_param: 0.1
  extra_param:
    - true
    - 10
    - 0.3
train:
  max_epoch: 100
  lr: 0.001
  mile_stones:
    - 150
  weight_decay: 0.0
  channel_int: null
  channel_weight_decay: null
log_file: exp_0
clean_save: true