task: train
random_seed: 123
exp_round: null
log_file: default
gpu_idx: 0
ckpt_root: null
ckpt_dir: null
save_tag: null
other_saved: null
clean_save: False
pytest: False
pipeline: Pipeline
num_workers: 0
mitigation_readout: null
mitigation_virtual: null
mitigation_expl_scores: default
mitigation_expl_scores_topk: -1
expval_budget: 8 # Added by Steve
numsamples_budget: 800 # Added by Steve
fidelity_alpha_2: 0.9 # Added by Steve
nec_alpha_1: 0.05 # Added by Steve
feat_int_alpha: 0.2 # Added by Steve
average_edge_attn: default # Added by Steve
save_metrics: False # Added by Steve
intervention_distrib: model_dependent # Added by Steve
acc_givenR: False # Added by Steve
mask: False # Added by Steve
metrics: "" # Added by Steve
debias: True # Added by Steve
random_expl: False # Added by Steve
samplingtype: deconfounded # Added by Steve
nec_number_samples: prop_G_dataset # Added by Steve
global_side_channel: null # Added by Steve
use_norm: bn # Added by Steve
log_id: ""
splits: ""
ratios: ""
wandb: False  # Added by Steve
train:
  channel_int: 2 # Added by Steve
  channel_weight_decay: 0.0 # Added by Steve
  combinator_weight_decay: 0.0 # Added by Steve
  end_temp: 0.3 # Added by Steve
  weight_decay: 0.
  save_gap: 10
  tr_ctn: False
  epoch: 0
  ctn_epoch: 0
  alpha: 0.2  # parameter for DANN
  stage_stones: []
  pre_train: 0
  l_norm_coeff: 1
  entr_coeff: 0.8
model:
  dim_hidden: 300
  dim_ffn: 300
  dropout_rate: 0.5
dataset:
  dataloader_name: BaseDataLoader
  dataset_root: null
  generate: False
  dim_node: null
  dim_edge: null
  num_classes: null
  num_envs: null
  feat_dims: null
  edge_feat_dims: null
ood:
  extra_param: null