includes:
  - ../base.yaml
model:
  model_layer: 5
  global_pool: mean
  dim_hidden: 300
  dim_ffn: 300
  dropout_rate: 0.3
train:
  num_steps: 10
  mile_stones: [150]
  max_epoch: 100
  lr: 0.001
  train_bs: 128
  val_bs: 256
  test_bs: 256
  weight_decay: 0.001
  lr_filternode: 0.001
  channel_weight_decay: 0.001
  combinator_weight_decay: 0.001
  channel_int: null
  end_temp: 0.6
dataset:
  dataset_name: BBBP
  domain: basis
  generate: false