includes:
  - base.yaml
model:
  model_name: DIRGIN
ood:
  ood_alg: DIR
  ood_param: 0.8 # explanation size ratio
  extra_param:
    - 0.1 # alpha
train:
  mile_stones:
    - 150
  lr: 0.0001
log_file: exp_0
clean_save: true