includes:
  - base.yaml
model:
  model_name: GSATGIN
  global_pool: sum
ood:
  ood_alg: GSAT
  ood_param: 1
  extra_param:
    - true
    - 10
    - 0.5
train:
  pre_train: 0
  mile_stones: [150]
log_file: exp_0
clean_save: true
