includes:
  - base.yaml
model:
  model_name: SMGNNGIN
  global_pool: sum
ood:
  ood_alg: SMGNN
  ood_param: 0.001
  extra_param:
    - true
    - 10
    - 0.01
train:
  pre_train: 0
  max_epoch: 100
  lr: 0.001
  mile_stones:
    - 150
  weight_decay: 0.0
  channel_int: null
  channel_weight_decay: 0.0
  combinator_weight_decay: 0.0
log_file: exp_0
clean_save: true
