includes:
  - base.yaml
model:
  model_name: GiSSTGIN
  global_pool: sum
ood:
  ood_alg: GiSST
  ood_param: null
  extra_param:
    - true
    - 0.01
    - 0.01
    - 0.01
    - 0.01
train:
  pre_train: 0
  mile_stones:
    - 150
log_file: exp_0
clean_save: true
