includes:
  - base.yaml
model:
  model_name: SMGNNGIN
  global_pool: sum
ood:
  ood_alg: SMGNN
  ood_param: 0.001
  extra_param:
    - true
    - 10
    - 0.01
train:
  pre_train: 0
  max_epoch: 100
  lr: 0.001
  mile_stones:
    - 150
  weight_decay: 0.1 # 1/2/6/8 good seeds AIDSC1 SMGNN temp with wd0.0 | 8/7/6/5/2/1 good seeds AIDSC1 SMGNN temp with wd0.01 | all but 10 good seeds AIDSC1 SMGNN temp with wd0.1. All done with combinator_wd=0.0
  channel_int: null
  channel_weight_decay: 0.0
  combinator_weight_decay: 0.1
log_file: exp_0
clean_save: true
