includes:
  - ../base.yaml
model:
  model_layer: 3
  global_pool: mean
  dim_hidden: 100
  dim_ffn: 100
  dropout_rate: 0.0
train:
  num_steps: 10
  max_epoch: 100
  weight_decay: 0.
  lr_filternode: 0.005
dataset:
  dataset_name: AIDS
  domain: basis
  generate: false
use_norm: none