includes:
  - ../base.yaml
model:
  model_layer: 3
  dim_hidden: 300
  dim_ffn: 300
  dropout_rate: 0.5
train:
  num_steps: 10
  mile_stones: [150]
  max_epoch: 200
  train_bs: 512
  val_bs: 1024
  test_bs: 1024
  lr: 0.001
  weight_decay: 0.
  