includes:
  - base.yaml
model:
  model_name: GiSSTGIN
  global_pool: sum
ood:
  ood_alg: GiSST
  ood_param: null
  extra_param:
    - true
    - 0.01
    - 0.1
    - 0.1
    - 0.01
train:
  pre_train: 0
  max_epoch: 100
  lr: 0.001
  mile_stones:
    - 150
  weight_decay: 0.0
  channel_int: 0.1
  channel_weight_decay: 0.00
log_file: exp_0
clean_save: true
use_norm: bn