includes:
  - base.yaml
model:
  model_name: GSATGIN
ood:
  ood_alg: GSAT
  ood_param: 1.0
  extra_param:
    - true
    - 10
    - 0.5
train:
  weight_decay: 0.01
log_file: exp_0
clean_save: true
use_norm: none