includes:
  - base.yaml
model:
  model_name: GSATGIN
ood:
  ood_alg: GSAT
  ood_param: 1
  extra_param:
    - true
    - 10
    - 0.01
train:
  max_epoch: 100
  lr: 0.001
  mile_stones:
    - 150
  weight_decay: 0.0
  channel_int: 2
  channel_weight_decay: 0.01
log_file: exp_0
clean_save: true
