includes:
  - ../base.yaml
model:
  model_layer: 3
  global_pool: mean
train:
  mile_stones:
    - 150
  train_bs: 64
  val_bs: 512
  test_bs: 512
  num_steps: 10
  lr: 0.001
  lr_filternode: 0.005
  weight_decay: 0.0
  channel_weight_decay: 0.0