includes:
  - ../base.yaml
model:
  model_layer: 3
  global_pool: sum
  dim_hidden: 64
  dim_ffn: 64
  dropout_rate: 0.3
train:
  num_steps: 10
  mile_stones: [150]
  max_epoch: 100
  train_bs: 128
  val_bs: 128
  test_bs: 128
  weight_decay: 0.001
  lr: 0.001
  lr_filternode: 0.001
  channel_weight_decay: 0.001
  combinator_weight_decay: 0.001
  channel_int: null
  end_temp: 0.6
dataset:
  dataset_name: MUTAG
  domain: basis
  generate: false
use_norm: none