includes:
  - ../base.yaml
model:
  model_layer: 3
  global_pool: sum
  dim_hidden: 64
  dim_ffn: 64
  dropout_rate: 0.3
train:
  num_steps: 10
  mile_stones: [150]
  max_epoch: 100
  train_bs: 128
  val_bs: 256
  test_bs: 256
  weight_decay: 0.
dataset:
  dataset_name: MUTAG
  domain: basis
  generate: false