includes:
  - base.yaml
model:
  model_name: GiSSTGIN
ood:
  ood_alg: GiSST
  ood_param: null
  extra_param:
    - true
    - 0.1
    - 0.1
    - 0.1
    - 0.1
log_file: exp_0
clean_save: true
use_norm:	bn
