includes:
  - base.yaml
model:
  model_name: GiSSTGIN
ood:
  ood_alg: GiSST
  ood_param: null
  extra_param:
    - true
    - 0.01
    - 0.1
    - 1
    - 0.1
train:
  max_epoch: 100
  lr: 0.001
  mile_stones:
    - 150
  weight_decay: 0.0
  channel_int: null
  channel_weight_decay: null
  train_bs: 64
  val_bs: 512
  test_bs: 512
log_file: exp_0
clean_save: true
use_norm:	bn
