includes:
  - base.yaml
model:
  model_name: GSATGIN
ood:
  ood_alg: GSAT
  ood_param: 1
  extra_param:
    - true
    - 20
    - 0.7
train:
  max_epoch: 200
  lr_filternode: 0.001
log_file: exp_0
clean_save: true
