includes:
  - base.yaml
model:
  model_name: GIN
  global_pool: sum
  model_layer: 1 # to account for mitigation_raw in SEGNNs
ood:
  ood_alg: ERM
  ood_param: -1.0
train:
  weight_decay: 0.05
log_file: exp_0
