includes:
  - base.yaml
model:
  model_name: GSATGIN
  global_pool: mean
  dim_hidden: 300
  dim_ffn: 300
  model_layer: 3
  dropout_rate: 0.5
ood:
  ood_alg: GSAT
  ood_param: 1.0
  extra_param:
    - true
    - 20
    - 0.7
train:
  train_bs: 256
  val_bs: 1024
  test_bs: 1024
  max_epoch: 200
  lr: 0.001
  lr_filternode: 0.001
  weight_decay: 0.0  # Default was 0.0
  channel_int: null
  channel_weight_decay: 0.0
  combinator_weight_decay: 0.0
  end_temp: 0.5
log_file: exp_0
