includes:
  - base.yaml
model:
  model_name: SMGNNGIN
  global_pool: mean
ood:
  ood_alg: SMGNN
  ood_param: 0.001
  extra_param:
    - true
    - 10
    - 0.01
train:
  lr_filternode: 0.001
  weight_decay: 0.05
  channel_int: null
  channel_weight_decay: 0.05 # Model trained was 0.1
  combinator_weight_decay: 0.05 # Model trained was 0.5
  end_temp: 0.6 # Model trained was 0.5
log_file: exp_0
clean_save: true
