includes:
  - base.yaml
model:
  model_name: SMGNNGIN
  global_pool: mean
  dim_hidden: 300
  dim_ffn: 300
  model_layer: 3
  dropout_rate: 0.5
ood:
  ood_alg: SMGNN
  ood_param: 0.001
  extra_param:
    - true
    - 10
    - 0.01
train:
  train_bs: 256
  val_bs: 1024
  test_bs: 1024
  max_epoch: 200
  lr: 0.001
  lr_filternode: 0.001
  weight_decay: 0.1  # Default was 0.0
  channel_int: null
  channel_weight_decay: 0.1
  combinator_weight_decay: 0.5
  end_temp: 0.5
log_file: exp_0
clean_save: true
