includes:
  - base.yaml
model:
  model_name: SMGNNGIN
  global_pool: sum
  dim_hidden: 64
  dim_ffn: 64
  model_layer: 3
  dropout_rate: 0.3
ood:
  ood_alg: SMGNN
  ood_param: 0.001
  extra_param:
    - true
    - 10
    - 0.01
train:
  train_bs: 128
  val_bs: 256
  test_bs: 256
  max_epoch: 100
  lr: 0.001
  lr_filternode: 0.001
  weight_decay: 0.01
  channel_int: null
  channel_weight_decay: 0.01
  combinator_weight_decay: 0.01
  end_temp: 0.6
log_file: exp_0
clean_save: true
