includes:
  - ../base.yaml
model:
  model_layer: 3
  global_pool: sum
  dim_hidden: 100
  dim_ffn: 100
  dropout_rate: 0.3
train:
  num_steps: 10
  mile_stones: [150]
  max_epoch: 100
  train_bs: 256
  val_bs: 512
  test_bs: 512
  lr: 0.001
  lr_filternode: 0.001
  weight_decay: 0.001
  channel_weight_decay: 0.001
  combinator_weight_decay: 0.001
  channel_int: null
  end_temp: 0.8
  combinator_temp: 2.0
dataset:
  dataset_name: MNIST
  domain: basis
  generate: false
use_norm: none