includes:
  - base.yaml
model:
  model_name: GSATGIN
ood:
  ood_alg: GSAT
  ood_param: 1
  extra_param:
    - true
    - 10
    - 0.7
log_file: exp_0
clean_save: true
# Results in the official GSAT paper are referred to a PNA backbone. We reproduce the results in the RAGE paper, where GSAT hasi GIN backbone