includes:
  - base.yaml
model:
  model_name: CIGAvGIN
ood:
  ood_alg: CIGA
  ood_param: 0.6
  extra_param:
    - 4
    - 1
train:
  train_bs: 512
  val_bs: 512
  test_bs: 512
  max_epoch: 100
  lr: 0.001
  mile_stones:
    - 300
  weight_decay: 0.0
log_file: exp_0
clean_save: true
num_workers: 2
